apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: apps
spec:
  encryptedData:
    key: AgBf6QPiu1e3WljLbv1DsJ3uFHYoYJkwZtNip+Iu+BT0QW1T17Z02kSczeAsQqAWoFHJpmcnhX3qDlN73MqpsqBCq3QbolDKUC8uDbGUcKgTacpMdAsuyrrR8mL/k73wrPJeBPHzsxOhnj8ep8n4jhAj3Sc8oSRdipIkoNgI+h1qHMKsPL7kccz+nxZT7+HTmG03E58TGnntBZl++qJ0NR7Nt5hY/1ke4qOUpdhuN7z3qOpgUH+KPbtRNj9qo4AqAIqtm+uOU5d41J9H5pqKz0BgwJSwcU//CJMKyicJYoZM73bn7VVoPM0goNxLteh5rD7+y+LrY717SuDdTrFNYevE7pP3mz6Fd9RGmaCqegToL4/ap106iwwBz1v7b4ZjSCXQX9l/xzPmdTPmCXBxEpZn6M4t3vjC9vlqarCRFTB9Eg2JjNyLcvT1r64Lf11O45wkiVjmoJ0CexBt0EiwzUu2MPqblUQti/7uzmuRbthkny8Due1YACBb3IOoaGQIgshPbnI/JASKdRAVe3Y29E5NXfWXeZARQ6JNSfG+IS2jelY/5VKaEtxKyk24iQ32bTwltdTAN/eQCH6PNF5FhdQKMeUP3kWtg3DlGX+bfA2DPqme1XQdWxAjJKWrXeTW0whrRXpy/ChYqFy6bQFT0rWdbS/Wi1bFmK78ktXpRCWHtJXwRSxBviv4xUqMZoCxcwpCGcLnPQ==
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: apps

